# Generated by Django 4.2.13 on 2024-06-17 14:55

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TaxForm',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tax_form', models.FileField(upload_to='tax_forms')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TaxField',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tax_field', models.CharField(choices=[('total_income', 'Total Income'), ('adjusted_gross_income', 'Adjusted Gross Income'), ('deductions', 'Deductions'), ('taxable_income', 'Taxable Income'), ('total_tax', 'Total Tax'), ('total_payments', 'Total Payments'), ('overpaid', 'Overpaid'), ('amount_owed', 'Amount Owed')], default='total_income', max_length=50)),
                ('instruction_text', models.CharField(max_length=255)),
                ('instruction_matched_pattern', models.CharField(max_length=255)),
                ('value_text', models.CharField(max_length=255)),
                ('value_normalized_text', models.CharField(max_length=255)),
                ('value_in_numeric', models.DecimalField(decimal_places=2, max_digits=10)),
                ('value_matched_pattern', models.CharField(max_length=255)),
                ('page_number', models.IntegerField(default=-1)),
                ('tax_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tax_fields', to='TaxParsingAPI.taxform')),
            ],
        ),
    ]
